package br.com.jdbcpp.dao;

import br.com.jdbcpp.api.DAO;
import br.com.jdbcpp.api.method.write.Command;
import br.com.jdbcpp.dto.user.insert.UserInsertPKUUIDDTO;

import java.sql.SQLException;
import java.util.UUID;

@DAO
public interface InsertUserDAO {

    @Command(value = """
            INSERT INTO users (user_identifier, first_name, last_name, email, birth_date)
            VALUES (:user_identifier:, :firstName:, :lastName:, :email:, :birthDate:)
            """, autoGeneratedPKNameOrIndex = "id")
    UUID insertReturnUUIDPK(final UserInsertPKUUIDDTO dto) throws SQLException;

    @Command(value = """
            INSERT INTO users (user_identifier, first_name, last_name, email, birth_date)
            VALUES (:user_identifier:, :firstName:, :lastName:, :email:, :birthDate:)
            """)
    void insertSQLServer(final UserInsertPKUUIDDTO dto) throws SQLException;

}
