CREATE TABLE order_items (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER(19,0) NOT NULL,
    order_id NUMBER(19,0) NOT NULL,
    amount NUMBER(10,0) NOT NULL,
    price NUMBER(10, 2) NOT NULL,
    CONSTRAINT fk_order_items_products FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_order_items_orders FOREIGN KEY (order_id) REFERENCES orders(id)
);