CREATE TABLE payments (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER(19,0) NOT NULL,
    amount NUMBER(10, 2) NOT NULL,
    payment_date TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_payments_orders FOREIGN KEY (order_id) REFERENCES orders(id)
);
