CREATE TABLE products (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code RAW(16) NOT NULL,
    name VARCHAR2(100) NOT NULL,
    description CLOB NOT NULL,
    sale_price NUMBER(10, 2) NOT NULL,
    buy_price NUMBER(10, 2) NOT NULL,
    stock_amount NUMBER(10, 0) NOT NULL,
    active NUMBER(1, 0) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    category_id NUMBER(19, 0) NOT NULL,
    CONSTRAINT fk_products_categories FOREIGN KEY (category_id) REFERENCES categories(id)
);
