CREATE TABLE orders (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    status VARCHAR(100) NOT NULL,
    user_id BIGINT NOT NULL,
    invoice_file VARBINARY(MAX),
    created_at DATETIME2 DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME2 DEFAULT CURRENT_TIMESTAMP
);
