CREATE TABLE categories (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    created_at DATETIMEOFFSET DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIMEOFFSET DEFAULT CURRENT_TIMESTAMP
);
