CREATE TABLE orders (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    status VARCHAR(100) NOT NULL,
    user_id UNIQUEIDENTIFIER NOT NULL,
    invoice_file VARBINARY(MAX),
    created_at DATETIMEOFFSET DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIMEOFFSET DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_orders_users FOREIGN KEY (user_id) REFERENCES users(id)
);
