CREATE TABLE users (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    birth_date DATE NOT NULL,
    created_at DATETIMEOFFSET DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIMEOFFSET DEFAULT CURRENT_TIMESTAMP
);
